/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalRouteImport } from './routes/withdrawal'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PicturepuzzleRouteImport } from './routes/picturepuzzle'
import { Route as MyGamesRouteImport } from './routes/my-games'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LudoRouteImport } from './routes/ludo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GameLobbyRouteImport } from './routes/game-lobby'
import { Route as FundwalletRouteImport } from './routes/fundwallet'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChessboardRouteImport } from './routes/chessboard'
import { Route as ChessRouteImport } from './routes/chess'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameRoomSessionIdRouteImport } from './routes/game-room.$sessionId'

const WithdrawalRoute = WithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PicturepuzzleRoute = PicturepuzzleRouteImport.update({
  id: '/picturepuzzle',
  path: '/picturepuzzle',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGamesRoute = MyGamesRouteImport.update({
  id: '/my-games',
  path: '/my-games',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LudoRoute = LudoRouteImport.update({
  id: '/ludo',
  path: '/ludo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLobbyRoute = GameLobbyRouteImport.update({
  id: '/game-lobby',
  path: '/game-lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const FundwalletRoute = FundwalletRouteImport.update({
  id: '/fundwallet',
  path: '/fundwallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessboardRoute = ChessboardRouteImport.update({
  id: '/chessboard',
  path: '/chessboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessRoute = ChessRouteImport.update({
  id: '/chess',
  path: '/chess',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomSessionIdRoute = GameRoomSessionIdRouteImport.update({
  id: '/game-room/$sessionId',
  path: '/game-room/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chess': typeof ChessRoute
  '/chessboard': typeof ChessboardRoute
  '/dashboard': typeof DashboardRoute
  '/fundwallet': typeof FundwalletRoute
  '/game-lobby': typeof GameLobbyRoute
  '/login': typeof LoginRoute
  '/ludo': typeof LudoRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-games': typeof MyGamesRoute
  '/picturepuzzle': typeof PicturepuzzleRoute
  '/register': typeof RegisterRoute
  '/withdrawal': typeof WithdrawalRoute
  '/game-room/$sessionId': typeof GameRoomSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chess': typeof ChessRoute
  '/chessboard': typeof ChessboardRoute
  '/dashboard': typeof DashboardRoute
  '/fundwallet': typeof FundwalletRoute
  '/game-lobby': typeof GameLobbyRoute
  '/login': typeof LoginRoute
  '/ludo': typeof LudoRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-games': typeof MyGamesRoute
  '/picturepuzzle': typeof PicturepuzzleRoute
  '/register': typeof RegisterRoute
  '/withdrawal': typeof WithdrawalRoute
  '/game-room/$sessionId': typeof GameRoomSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chess': typeof ChessRoute
  '/chessboard': typeof ChessboardRoute
  '/dashboard': typeof DashboardRoute
  '/fundwallet': typeof FundwalletRoute
  '/game-lobby': typeof GameLobbyRoute
  '/login': typeof LoginRoute
  '/ludo': typeof LudoRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-games': typeof MyGamesRoute
  '/picturepuzzle': typeof PicturepuzzleRoute
  '/register': typeof RegisterRoute
  '/withdrawal': typeof WithdrawalRoute
  '/game-room/$sessionId': typeof GameRoomSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chess'
    | '/chessboard'
    | '/dashboard'
    | '/fundwallet'
    | '/game-lobby'
    | '/login'
    | '/ludo'
    | '/marketplace'
    | '/my-games'
    | '/picturepuzzle'
    | '/register'
    | '/withdrawal'
    | '/game-room/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chess'
    | '/chessboard'
    | '/dashboard'
    | '/fundwallet'
    | '/game-lobby'
    | '/login'
    | '/ludo'
    | '/marketplace'
    | '/my-games'
    | '/picturepuzzle'
    | '/register'
    | '/withdrawal'
    | '/game-room/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/chess'
    | '/chessboard'
    | '/dashboard'
    | '/fundwallet'
    | '/game-lobby'
    | '/login'
    | '/ludo'
    | '/marketplace'
    | '/my-games'
    | '/picturepuzzle'
    | '/register'
    | '/withdrawal'
    | '/game-room/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChessRoute: typeof ChessRoute
  ChessboardRoute: typeof ChessboardRoute
  DashboardRoute: typeof DashboardRoute
  FundwalletRoute: typeof FundwalletRoute
  GameLobbyRoute: typeof GameLobbyRoute
  LoginRoute: typeof LoginRoute
  LudoRoute: typeof LudoRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyGamesRoute: typeof MyGamesRoute
  PicturepuzzleRoute: typeof PicturepuzzleRoute
  RegisterRoute: typeof RegisterRoute
  WithdrawalRoute: typeof WithdrawalRoute
  GameRoomSessionIdRoute: typeof GameRoomSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawal': {
      id: '/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof WithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picturepuzzle': {
      id: '/picturepuzzle'
      path: '/picturepuzzle'
      fullPath: '/picturepuzzle'
      preLoaderRoute: typeof PicturepuzzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-games': {
      id: '/my-games'
      path: '/my-games'
      fullPath: '/my-games'
      preLoaderRoute: typeof MyGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ludo': {
      id: '/ludo'
      path: '/ludo'
      fullPath: '/ludo'
      preLoaderRoute: typeof LudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-lobby': {
      id: '/game-lobby'
      path: '/game-lobby'
      fullPath: '/game-lobby'
      preLoaderRoute: typeof GameLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundwallet': {
      id: '/fundwallet'
      path: '/fundwallet'
      fullPath: '/fundwallet'
      preLoaderRoute: typeof FundwalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chessboard': {
      id: '/chessboard'
      path: '/chessboard'
      fullPath: '/chessboard'
      preLoaderRoute: typeof ChessboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess': {
      id: '/chess'
      path: '/chess'
      fullPath: '/chess'
      preLoaderRoute: typeof ChessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-room/$sessionId': {
      id: '/game-room/$sessionId'
      path: '/game-room/$sessionId'
      fullPath: '/game-room/$sessionId'
      preLoaderRoute: typeof GameRoomSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChessRoute: ChessRoute,
  ChessboardRoute: ChessboardRoute,
  DashboardRoute: DashboardRoute,
  FundwalletRoute: FundwalletRoute,
  GameLobbyRoute: GameLobbyRoute,
  LoginRoute: LoginRoute,
  LudoRoute: LudoRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyGamesRoute: MyGamesRoute,
  PicturepuzzleRoute: PicturepuzzleRoute,
  RegisterRoute: RegisterRoute,
  WithdrawalRoute: WithdrawalRoute,
  GameRoomSessionIdRoute: GameRoomSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
